### ISSUE TITLE
Post-intallation errors.

### ISSUE THREAD

**Issue by Dharhix** [MarkVelez/godot-modular-settings-menu#1]
The info is in the pic. It's on Godot 4.3.stable.

![image](https://github.com/user-attachments/assets/7fe0005a-11d4-44f6-8f33-c4a3e09975e0)

I haven't touched anything yet. Should I be worried? Will it work?

**Comment by MarkVelez** [comment]
It is most likely due to you not enabling the plugin as doing so adds the singleton that those scripts rely on. To enable the plugin you can go to `Project > Project Settings... > Plugins`. There you should see the plugin and just enable it then reload your project.

**Comment by Dharhix** [comment]
The messages are generated right after the install process finishes. I didn't have the time to even try to use it or add it to the list of singletons.

That's why I was asking if there was something going on.

**Comment by MarkVelez** [comment]
Like I said, you don't have to add the singleton manually, just enable the plugin and restart your project. Those errors are expected.

I will assume that the issue is fixed.
